name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - pip
  - requests
  - ipycanvas
  - ipywidgets
  - ipyleaflet
  - jinja2
  - numpy  
  - matplotlib
  - pandas
  - scipy
  - plotly
  - networkx
  - pydot
  - simpy
  - sympy
